### PR TITLE
Fixed an issue with a variable called module

### PR DESCRIPTION
**Pull request by elpic**
Remove unused less files & fixed an issue with a variable called module

### CODE REVIEW

**Comment by nohros** [comment]
Why the .less files was removed?

**Comment by elpic** [comment]
I thought it was not used.

**Comment by nohros** [comment]
The name of the main file was changed too, why?

**Comment by elpic** [comment]
To be consistent with other files on the project.

**Comment by nohros** [comment]
The main project file is the nsPopover.js and all the other files should follows the rules defined by it.

**Comment by nohros** [comment]
It is not clear was waht issue was resolved, can you explain?

**Pull request closed without merging**
